<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'sLjA/Q==');
$cfg_Cs[2]=array(0,1,1,'udjT2s7Sw8c=');
$cfg_Cs[3]=array(0,1,1,'warPtc7Sw8c=');
$cfg_Cs[4]=array(0,1,1,'vNPI687Sw8c=');
$cfg_Cs[5]=array(1,1,1,'sLK3wMnosbg=');
$cfg_Cs[6]=array(1,1,1,'s7XU2NPDxrc=');
$cfg_Cs[7]=array(1,1,1,'u/q158nosbg=');
$cfg_Cs[8]=array(1,1,1,'vNLTw7Xnxvc=');
$cfg_Cs[9]=array(1,1,1,'z/u30bXn19M=');
$cfg_Cs[10]=array(1,1,1,'0r3Bxsnosbg=');
$cfg_Cs[11]=array(2,1,1,'us/X97/Nu6c=');
$cfg_Cs[12]=array(2,1,1,'t/7O8cH3s8w=');
?>