<div class="box935_t"></div>	
<div class="member box935_m">	
<div class='join_img'><img src="[field:litpic/]"/></div>	
<div class='join_desc'><h1><a href="[field:arcurl/]" class="y">[field:title/]</a></h1></div>
<!--236*35-->	
<div class="words fl aboutus_text">		
<p id='join_description' style="margin:0 8px 0 0;">[field:description/]</p>
</div>	
</div>
<div class="box935_b"></div>
<div class="clear"></div>