<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:product_desc itemname="【案例】产品简介" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:product_desc>
<field:copyright itemname="【案例】Copyright" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:copyright>
<field:time itemname="【案例】Time" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:time>
<field:product_name_en itemname="【案例】产品英文名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:product_name_en>
<field:product_name_cn itemname="【案例】产品中文名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:product_name_cn>
