<li class="">				
<div class="case_w" href="#">									
<img src="[field:litpic/]" id="img1" width="262" height="148">
<!--进入页面时看到的缩略图-->					
<div class="fire"></div>										
<a href="[field:picname/]" rel="lightbox[roadtrip]" class="x" title="[field:title function='html2text(@me)'/]"></a>
<!--点击放大镜，通过灯箱效果看到的大图-->					
<a href="[field:arcurl/]" class="y"></a>
<!--点击链接进入的页面URL-->									
</div>			
</li>